name: ${pluginName}
main: ${pluginMainClass}
version: "${pluginVersion}"
api: "${pluginApiVersion}"
load: POSTWORLD
author: ${pluginAuthor}
description: High level NPC API and plugin for PowerNukkitX.
permissions:
  npcs.command.use:
    default: op
